### ISSUE TITLE
startOfWeek should accept a Weekday parameter 

### ISSUE THREAD

**Issue by n1k0** [waratuman/time-extra#1]
Some areas of the World have their weeks starting on Sundays, some other on Mondays. Google Calendar even has an option to make them start on Saturday haha.

Anyway, I think the `startOfWeek` function should accept a `Time.Weekday` parameter to make it more configurable and locale-agnostic.

Something along this line:

```elm
startOfWeek : Zone -> Weekday -> Posix -> Posix
```

What do you think? I can work on a PR if you agree.

Edit: if accepted, this evolution should also be ported to other functions like `endOfWeek`, `weekdayFromInt` and friends.

**Comment by waratuman** [comment]
The current implementation allows you to set the start of the week. The function signature is exactly as you suggested. (See https://package.elm-lang.org/packages/waratuman/time-extra/1.1.0/Time-Extra#startOfWeek)

For the `weekdayFromInt` function I was just following the JavaScript standards. I'd recommend just defining your own function if it is different.

**Comment by n1k0** [comment]
Wow. This is were I realize I'm having a tough `startOfWeek` myself... Sorry for the noise.
